### ISSUE TITLE
Buttons on the (sub-)diagram

### ISSUE THREAD

**Issue by slisson** [slisson/mps-diagram-editor#176]
They are always visible.

- Relayout
- Relayout edges

**Comment by markusvoelter** [comment]
Well..... if you have them on the sub diagram, why not also have them on the top level diagram and remove the two ugly "Layout" and "Layout Edges" buttons from the palette? Would be more consistent.

**Comment by slisson** [comment]
That's why "sub" is in parentheses.

**Comment by markusvoelter** [comment]
ah :-)

2015-04-01 11:12 GMT+02:00 Sascha Lißon <notifications@github.com>:

> That's why "sub" is in parentheses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slisson/mps-diagram-editor/issues/176#issuecomment-88407388>
> .
>



-- 
Dr. Markus Völter

voelter - ingenieurbüro für softwaretechnologie  ::  itemis AG Stuttgart
voelter@acm.org  ::  http://www.voelter.de  ::  +49 (0) 171 / 86 01 869

http://dslbook.org  ::  Domain Specific Language Engineering book
http://mbeddr.com  ::  Extensible Languages for Embedded Software
http://omegataupodcast.net  ::  Science and Engineering in your Headphones
